### ISSUE TITLE
Export only flagged files

### ISSUE THREAD

**Issue by stanbar** [devidw/obsidian-to-hugo#11]
Hello,
Is there a way of exporting only certain files. For example flagged with "export: true" in frontmatter?
Moreover, links to files that are not exported should also be omitted. 
For example, I have three files, and only two of them are `exported`.

`I like.md`
```markdown
---
export: true
---

I like:
- [[I like motorcycles]]
- [[I like cars]]
```

`I like motorcycles.md`
```markdown
---
export: true
---
I like Honda Africa twin
```

`I like cars.md`
```markdown

```

The result would be

`I like.md`
```markdown
I like:
- [I like motorcycles]({{< ref "I like motorcycles" >}})
- I like cars
```

`I like motorcycles.md`
```markdown
I like Honda Africa twin
```

`processors` seem not to be ideal as they do they just transform the content of files not filter the list of files.

**Comment by stanbar** [comment]
Something like https://github.com/ObsidianPublisher/obsidian-github-publisher  "share: true" frontmatter entry.

**Comment by stanbar** [comment]
Actually, merging those two project would be the best option I guess.
I would require creating a Hugo template for https://github.com/ObsidianPublisher/obsidian-github-publisher

**Comment by devidw** [comment]
Hey @stanbar 

I added a filters feature, which allows you to register a custom filter function

You have access to the file path and the file contents inside your filter function

When you return true, the file will be processed, otherwise it will be skipped

With this functionality added, you should be able to implement what you are looking for by writing a custom filter, parsing the content's frontmatter and doing the desired checks

Feel free to check out the test case, as long as this is not documented in the readme:

https://github.com/devidw/obsidian-to-hugo/blob/b0cd29520d7053827b9c1a545c069ad00db705de/tests/e2e_cli.py#L43-L50

**Comment by vcavallo** [comment]
Unless I'm mistaken, the `path` here is actually just the filename, not the path including directory names. In the test, the filename of the file under test is `include.md`. The test will not pass if there is an arbitrarily named file within an `include` directory.

**Comment by vcavallo** [comment]
https://github.com/devidw/obsidian-to-hugo/blob/60290a8174591a8f1b5b8b46acd47a72546f1972/src/obsidian_to_hugo/obsidian_to_hugo.py#L68

The argument `file` here is just the filename.
